### ISSUE TITLE
How do I run this project, ready?

### ISSUE THREAD

**Issue by Anderson-Juhasc** [isocolsky/bitcore-wallet-service#32]

**Comment by matiu** [comment]
stay subscribed to https://github.com/bitpay/bitcore-wallet-service
it will be ready in the next weeks.

On Mon, Feb 16, 2015 at 7:51 PM, Anderson Juhasc <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isocolsky/bitcore-wallet-service/issues/32>.
>



-- 
BitPay.com
